// ============================================================================
// DICCIONARIO DE CAMPOS del simulador → realidad del código.
// Cada label del flow abre el sidebar (FieldInfoPanel) con: dónde se GUARDA (tables),
// en qué CAPA vive la lógica (layers), su ESTADO (status) y el detalle.
// Fuente: censo verificado docs/codigo/CENSO-CAMPOS-CONFIG.md + flow/MAP.md (S4 burós)
// + docs/codigo/ONBOARDING-DATOS-DECISION-ANALISIS.md. Fecha: 2026-07-11.
//
// status:
//   decide    → cambia la OFERTA (elegibilidad / cupo / cuota / plazo / listado).
//   display   → solo se muestra o se entrega; ningún cálculo decide con él.
//   kyc       → identidad / antifraude; no decide el listado (el flow no modela KYC a fondo).
//   pisado    → se guarda, pero otro valor lo sobrescribe antes de usarse.
//   muerto    → la columna existe pero ningún cálculo la lee.
//   servicing → se usa post-desembolso (cartera), no en la oferta.
// layers: application · application-vue · legacy-backend · frontend-monorepo · pre-approvals · bd
// ============================================================================

export const FIELD_STATUS = {
  decide:    { label: 'Decide',    hint: 'Cambia la oferta: elegibilidad, cupo, cuota, plazo o el listado.' },
  display:   { label: 'Solo muestra', hint: 'Se muestra o se entrega, pero ningún cálculo decide con este dato.' },
  kyc:       { label: 'Identidad/KYC', hint: 'Sirve para validar identidad o antifraude; no decide el listado de crédito.' },
  pisado:    { label: 'Se pisa',   hint: 'Se guarda, pero otro valor lo sobrescribe antes de decidir o mostrarse.' },
  muerto:    { label: 'No se usa', hint: 'La columna existe en la base de datos, pero ningún cálculo la lee.' },
  servicing: { label: 'Servicing', hint: 'Se usa después del desembolso (cartera/cobranza), no en la oferta.' },
}

export const LAYER_LABELS = {
  'application':        'application · backend vivo (PHP)',
  'application-vue':    'application · front Vue (Inertia, old-screens)',
  'legacy-backend':     'legacy-backend · reescritura (Laravel Modules)',
  'frontend-monorepo':  'frontend-monorepo · wizard (React)',
  'pre-approvals':      'pre-approvals-service · microservicio (Go)',
  'bd':                 'solo dato en BD (sin lógica)',
}

export const FIELD_DOCS = {
  // ── SOLICITUD (inputs del cliente → user_requests) ─────────────────────────
  'sol.monto': { label: 'Monto', tables: ['user_requests.amount / original_amount'], layers: ['application', 'legacy-backend', 'frontend-monorepo'], status: 'decide',
    summary: 'Lo que pide el cliente. Se captura ANTES de crear la solicitud y viaja por 3 orígenes según el canal.',
    detail: 'Cruza la regla de rango (min/max_amount) y define el tramo por monto + el cupo. Orígenes: session (asesor), query base64 (ecommerce), body del OTP (wizard). Número mágico 180000 como default si el front no lo manda (LenderListingController:21).' },
  'sol.cuotaInicial': { label: 'Cuota inicial (pago)', tables: ['user_requests.initial_fee'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'El enganche que el cliente paga por adelantado. El % lo EXIGE la categoría (rt=2), no el comercio.', pisaPor: 'category.min_initial_fee define el %; acá se congela el monto',
    detail: 'Se resta del capital antes de la anualidad (PaymentCalculationService:187). El monto lo cobra Wompi (InitialFeePaymentService:77). Si el % del comercio y el de la categoría difieren, manda la categoría.' },
  'sol.salario': { label: 'Salario declarado', tables: ['user_field_values (field_id 87)'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Solo se pide si el buró (Ágil/Mareigua/Ábaco/Quanto) no reportó ingreso. Última prioridad de la cascada.',
    detail: 'Cuando entra por declarado, cuenta como ingreso NO verificado → puede fallar reglas con verified_income (rt=2). En el flow es fiel: solo aparece si ambas fuentes de buró están null.' },
  'sol.nombre': { label: 'Nombre', tables: ['users / user_requests'], layers: ['bd'], status: 'display',
    summary: 'Identidad del solicitante. No decide nada del listado.',
    detail: 'En el simulador se deriva del documento (determinístico, coherente con el género). Solo display.' },
  'sol.apellido': { label: 'Apellido', tables: ['users / user_requests'], layers: ['bd'], status: 'display',
    summary: 'Identidad del solicitante. No decide nada.', detail: 'Derivado del perfil determinístico en el simulador. Solo display.' },
  'sol.tipoDoc': { label: 'Tipo de documento', tables: ['users.document_type'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'CC / CE / PEP. Algunas entidades restringen el tipo (regla documentTypes / group_rule).',
    detail: 'Cuidado: "PEP" acá es Permiso Especial de Permanencia (migratorio, Motai renting), no Persona Expuesta Políticamente (AML).' },
  'sol.numDoc': { label: 'N° de documento', tables: ['users.document_number'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Identifica al cliente; dispara la consulta de buró (con frecuencia por aliado).',
    detail: 'En el simulador define el perfil de buró simulado (hash determinístico). En real, gatea la consulta a Experian (con datacredito_frequencies).' },
  'sol.fechaExp': { label: 'Fecha de expedición', tables: ['users / KYC'], layers: ['application', 'legacy-backend'], status: 'kyc',
    summary: 'En el simulador ninguna regla la usa. En real es dato de identidad (KYC), fuera del alcance del listado.',
    detail: 'El flow modela la decisión de crédito (listado/cupo), no la validación de identidad. La fecha de expedición se usa en el KYC (TusDatos/ADO), que el simulador no reproduce.' },

  // ── BURÓ · datos por proveedor (risk_central_user_data cifrado + EAV + user_summaries) ──
  'buro.score': { label: 'Score datacrédito', tables: ['risk_central_user_data.score', 'user_summaries.datacredito'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'El ÚNICO buró que da score es Experian/Datacrédito. Gatea 2 veces: datacrédito por sucursal + categoría.',
    detail: 'OAuth2 + POST /cs/credit-history/v1/hdcplus (producto Acierta). El reporte crudo se cifra con APP_KEY; el score se promedia. En local/dev se MOCKEA con ExperianFixture. Los 2 motores (viejo rt≠2 / nuevo rt=2) lo comparan con umbrales distintos.' },
  'buro.negatives12m': { label: 'Negativos 12m', tables: ['risk_central_user_data.data (principals)'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Reportes negativos del último año. Lo miran el datacrédito y la regla de categoría.',
    detail: '⚠️ Los 2 motores miden cosas distintas del mismo reporte: application usa additional_info.negativeAccounts.total (mapeado); legacy usa principals.negativeHistoricalLast12Months (crudo).' },
  'buro.currentArrears': { label: 'Mora vigente', tables: ['risk_central_user_data.data'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Cuentas HOY en mora. Es exclusiva de la regla de categoría (current_delinquencies).',
    detail: 'No la chequea el datacrédito temprano; solo la categoría al final del cascade (rt=2).' },
  'buro.inquiries6m': { label: 'Consultas 6m', tables: ['risk_central_user_data.data.principals'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Cuántas veces consultaron el buró en 6 meses. Regla consulted_last_6_months.',
    detail: 'Sólo el motor NUEVO (rt=2) la lee directo de data.principals; el viejo la ignora (no está en additional_info).' },
  'buro.creditHistoryMonths': { label: 'Antigüedad historial', tables: ['risk_central_user_data.data (maturationSince)'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Meses de vida crediticia (maduración). Regla financial_history_length.',
    detail: '⚠️ Comparador OPUESTO entre motores: el viejo rechaza con <= (RiskCentralValidationService:56); el nuevo con < estricto (DatacreditoRuleEvaluator:94). En el borde difieren.' },
  'buro.monthlyDebtPayment': { label: 'Cuota deuda/mes', tables: ['risk_central_user_data.data'], layers: ['application'], status: 'decide',
    summary: 'Cuánto paga por mes en deudas. Se usa para DERIVAR el endeudamiento (÷ ingreso).',
    detail: 'No es un umbral directo; alimenta la capacidad de pago / debt-to-income.' },
  'buro.quantoIncome': { label: 'Ingreso (Quanto)', tables: ['user_summaries.quanto', 'risk_central_user_data'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Ingreso ESTIMADO por el modelo Quanto de Experian. 4ª prioridad de la cascada de ingreso.',
    detail: 'Al procesar Quanto se fuerza EAV 29="Empleado" y 160="no" (hardcodeados) — el usuario queda marcado Empleado artificialmente.' },
  'buro.totalDebt': { label: 'Saldo deuda', tables: ['risk_central_user_data.data'], layers: ['application'], status: 'display',
    summary: 'Saldo total que debe hoy. Dato informativo: se entrega pero no decide.',
    detail: 'Aparece en el perfil enriquecido pero ninguna regla lo consume.' },
  'buro.disputes': { label: 'Disputas', tables: ['risk_central_user_data.data'], layers: ['application'], status: 'display',
    summary: 'Reclamos abiertos en el buró. Informativo, no decide.', detail: 'Se entrega y no se usa para el listado.' },
  'buro.agilIncome': { label: 'Ingreso (Ágil Data)', tables: ['user_summaries.agildata', 'user_field_values (87)'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Ingreso mensual de Ágil Data (aportes/nómina). 1ª prioridad de la cascada de ingreso.',
    detail: 'Fuente principal; si reporta, gana sobre Mareigua/Ábaco/Quanto/declarado. Alimenta capacidad de pago y reglas de ingreso.' },
  'buro.employment': { label: 'Ocupación', tables: ['user_field_values (field_id 29)', 'user_summaries.agildata'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Empleado/independiente/pensionado/desempleado. Regla de categoría (occupation) y group rules.',
    detail: '⚠️ Al procesar Quanto se ESCRIBE EAV 29="Empleado" hardcodeado — un usuario sin central puede quedar marcado empleado sin serlo.' },
  'buro.edad': { label: 'Edad', tables: ['users.age (de date_of_birth)'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Gate de varias reglas (group rules, categoría min/max_age; edad es el gate de CrediPullman).',
    detail: 'No viene del buró: se calcula de date_of_birth (TusDatos/Ágil o carga manual).' },
  'buro.gender': { label: 'Género', tables: ['users.gender'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Regla de categoría (gender) + motor demográfico (sin buró).', detail: 'Formato CSV con | en la regla; in_array contra el género del usuario.' },
  'buro.agilContinuity': { label: 'Continuidad (Ágil)', tables: ['user_summaries.agildata'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Meses cotizando de forma continua. Regla employment_continuity de la categoría.',
    detail: 'Buckets <3m/3m/6m/12m → meses. Ágil es 1ª fuente; Mareigua es el respaldo.' },
  'buro.mareiguaIncome': { label: 'Ingreso (Mareigua)', tables: ['user_summaries.mareigua'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Ingreso de Mareigua. 2ª prioridad (fallback de Ágil Data) en la cascada.',
    detail: 'Solo se usa si Ágil Data no reportó.' },
  'buro.mareiguaContinuity': { label: 'Continuidad (Mareigua)', tables: ['user_summaries.mareigua'], layers: ['application'], status: 'display',
    summary: 'Continuidad laboral de respaldo (si Ágil no reporta). Informativa salvo que sea la fuente activa.',
    detail: 'Entra a la regla de continuidad solo como fallback de Ágil.' },
  'buro.incomeTrend': { label: 'Tendencia de ingreso', tables: ['user_summaries.mareigua'], layers: ['application'], status: 'display',
    summary: 'Creciente/estable/decreciente. Informativa: no decide.', detail: 'Se entrega pero ninguna regla la consume.' },
  'buro.abacoIncome': { label: 'Ingreso (Ábaco · gig)', tables: ['user_summaries.abaco'], layers: ['application', 'legacy-backend'], status: 'display',
    summary: 'Ingreso de economía gig (Rappi/DiDi/Uber). En Motai renting es el underwriting alternativo.',
    detail: 'Proveedor EXTERNO (CreditOp solo integra su API): Ábaco pide las credenciales de acceso del cliente a cada plataforma, entra y devuelve el resumen de ingresos mensuales — pensado para población PEP/migrante sin buró. ⚠️ Divergencia: el resultado NO está cableado a la decisión en legacy (queda huérfano); el simulador lo mete en la cascada de ingreso — sobre-modela un poco vs el código real.' },
  'buro.identidad': { label: 'Identidad', tables: ['user_summaries.tusdatos', 'risk_central_user_data'], layers: ['application', 'legacy-backend'], status: 'kyc',
    summary: 'Validación de identidad (TusDatos). Puede ser una regla dura (requireVerifiedIdentity).',
    detail: 'KYC de identidad, no score. Si una regla la exige y no se validó → rechazo.' },
  'buro.listas': { label: 'Listas (AML)', tables: ['user_summaries.tusdatos'], layers: ['application', 'legacy-backend'], status: 'kyc',
    summary: 'Antilavado (AML): si aparece en listas restrictivas. Regla requireCleanAml.',
    detail: 'SmartPay salta el AML de TusDatos (canal). "PEP" en AML = Persona Expuesta Políticamente (distinto del PEP migratorio de Motai).' },
  'buro.docStatus': { label: 'Estado del documento', tables: ['user_summaries.tusdatos'], layers: ['application'], status: 'display',
    summary: 'Vigente/cancelado. Informativo en el flow.', detail: 'Dato de TusDatos que se entrega; no gatea el listado en el simulador.' },
  'buro.debtToIncome': { label: 'Endeudamiento', tables: ['derivado (cuota deuda ÷ ingreso)'], layers: ['application'], status: 'decide',
    summary: 'Nivel de deuda sobre el ingreso. DERIVADO, no es un dato directo del buró.',
    detail: 'cuota mensual de deuda (Experian) ÷ ingreso consolidado. Alimenta la capacidad de pago.' },

  // ── CALCULADORA del comercio (lenders_by_allieds) ──────────────────────────
  'calc.montoMax': { label: 'Monto máx', tables: ['lenders_by_allieds.max_amount', '← credit_line_by_lenders.max_amount'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Tope de cupo del comercio. HEREDA del rango de la entidad; el comercio puede pisarlo hacia abajo.',
    detail: 'Único campo de la calculadora con padre en la entidad: por defecto toma el máx del rango de la entidad (credit_line_by_lenders.max_amount) y el comercio (lenders_by_allieds.max_amount) puede topar por debajo. El punto gris = heredado del máx de la entidad; amarillo = el comercio puso su propio tope. Para rt=2 la categoría de perfilamiento puede acotar aún más.' },
  'calc.cargoFijo': { label: 'Cargo administrativo fijo', tables: ['lenders_by_allieds.administrative_fixed_value'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Costo fijo en $ que paga el CLIENTE financiado. Se suma al capital → sube la cuota.',
    detail: 'Entra en calculateAmounts (PromissoryNoteController:353 app / PaymentCalculationService legacy).' },
  'calc.costosAdmin': { label: 'Costos administrativos', tables: ['lenders_by_allieds.administrative_costs_percentage'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: '% del monto que paga el CLIENTE. Se suma al capital → sube la cuota.', detail: 'Cuota real (no decide elegibilidad).' },
  'calc.fondoGarantias': { label: 'Fondo de garantías', tables: ['lenders_by_allieds.guarantee_fund_percentage'], layers: ['application', 'legacy-backend'], status: 'pisado',
    summary: 'Colchón anti-impago (con IVA 19%). Suma al capital → sube la cuota.', pisaPor: 'category.FGA (rt=2) · RevolvingCredit.fga (rt=3)',
    detail: 'El valor del comercio solo sobrevive para in-platform SIN categoría; en rt=2 lo pisa el FGA de la categoría. El simulador usa el del comercio (simplificación fiel a rt≠2).' },
  'calc.seguroVidaVar': { label: 'Seguro de vida (variable)', tables: ['lenders_by_allieds.life_insurance_percentage'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Prima % que paga el CLIENTE, se suma a la cuota mensual.', detail: 'Alimenta el SOAP de Credifamilia en legacy.' },
  'calc.seguroVidaFijo': { label: 'Seguro de vida (fijo)', tables: ['lenders_by_allieds.life_insurance_fixed'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Prima fija mensual que paga el CLIENTE: se suma a la cuota.', detail: 'Cuota real.' },
  'calc.comision': { label: 'Comisión', tables: ['lenders_by_allieds.comission_percentage'], layers: ['application', 'legacy-backend'], status: 'display',
    summary: 'Lo que CreditOp le cobra al COMERCIO (%·final_amount), DESPUÉS de originar. No toca la cuota del cliente.',
    detail: 'Es liquidación/negocio, no oferta (UserRequest.php:127). Por eso no entra en la matemática de la cuota.' },
  'calc.cuotaInicial': { label: 'Cuota inicial (comercio)', tables: ['lenders_by_allieds.initial_fee_percentage'], layers: ['application-vue'], status: 'pisado',
    summary: 'Se guarda por comercio, pero para rt=2 el enganche real lo fija la categoría.', pisaPor: 'category.min_initial_fee (LenderRetrievalService:716)',
    detail: 'Solo tiene efecto en el flujo viejo old-screens de application (Confirmation.vue:587); en legacy es fantasma.' },
  'calc.iva': { label: 'IVA', tables: ['lenders_by_allieds.iva'], layers: ['application', 'legacy-backend'], status: 'muerto',
    summary: 'El cálculo real quema 19%; esta columna no se lee para calcular la cuota.',
    detail: 'El pagaré/plan hardcodea * (1 + 19/100) y la línea $lender->iva está comentada. En app se guarda 19 para rt=2. Solo variaría la cuota SIMULADA del front para rt≠2.' },
  'calc.castigo': { label: 'Castigo / gastos', tables: ['lenders_by_allieds.expense_penalties_percentage'], layers: ['application', 'legacy-backend'], status: 'muerto',
    summary: 'Se serializa al front en varios servicios, pero ningún cálculo de cuota lo consume.',
    detail: 'Ausente de PromissoryNoteController (app) y PaymentCalculationService (legacy).' },
  'calc.multiplo': { label: 'Múltiplo del ingreso', tables: ['lenders_by_allieds.multiple_of_maximum_amount'], layers: ['application', 'legacy-backend'], status: 'muerto',
    summary: 'Se pide y valida en el admin, pero la fórmula ingreso × factor no existe en ningún lado.',
    detail: 'El cupo rt=2 lo decide la categoría; max_amount viene directo, nunca multiplicado por este factor.' },

  // ── CONFIG DE ENTIDAD (credit_line_by_lenders + creditop_x_lender_configuration) ──
  'ent.producto': { label: 'Producto', tables: ['(no hay columna: response_type + path_id)'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Crédito / renting / renting con compra. product_type NO existe como columna: se modela con response_type + path (ej. path IMEI).',
    detail: 'El "tipo de producto" es fantasma en BD; se infiere. El renting/RTO real se gatea por modo del comercio + path, no por una columna de producto.' },
  'ent.monto': { label: 'Monto (entidad)', tables: ['credit_line_by_lenders.min_amount / max_amount'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Rango base que financia la entidad. Es la regla real que filtra por monto (rt≠2) y el piso rt=2.',
    detail: 'Puede ser pisado por el override del comercio y por la categoría (rt=2). El monto < min → rechazo below_min_amount.' },
  'ent.dues': { label: 'Nº de cuotas', tables: ['credit_line_by_lenders.fee_numbers'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Lista de plazos ofrecibles. El mín/máx (min/max_fee_number) se DERIVA de esta lista y se recorta por categoría + tramo.',
    detail: 'min_fee_number es fantasma en legacy (0 lecturas); max_fee_number se pisa por la categoría en rt=2.' },
  'ent.tasa': { label: 'Tasa', tables: ['credit_line_by_lenders.rate'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Tasa mensual vencida. Driver de la cuota y de la anualidad del cupo.', pisaPor: 'en legacy la pisa category.rate si está seteada',
    detail: '⚠️ Divergencia: en legacy category.rate pisa esta tasa (y el wizard la consume); en application category.rate se ignora. En el cupo entra solo si debt_capacity_amount_validation≠0.' },
  'ent.condonadas': { label: 'Cuotas condonadas', tables: ['creditop_x_lender_configuration.installments_waived_interest'], layers: ['application'], status: 'servicing',
    summary: 'El valor del form NO baja la cuota de la oferta; solo se copia al libro mayor (servicing).',
    detail: 'La cuota que sí baja por promociones usa promotions_by_lenders. El valor del form solo aterriza en el ledger post-aprobación.' },
  'ent.mora': { label: 'Tasa de mora', tables: ['creditop_x_lender_configuration.late_payment_interest_rate'], layers: ['application', 'legacy-backend'], status: 'servicing',
    summary: 'Post-desembolso (Estado 11+): no toca la oferta ni la cuota mostrada.',
    detail: 'Alimenta la causación diaria de intereses de mora sobre créditos ya desembolsados. El pagaré muestra "tasa máx legal".' },

  // ── PERFILAMIENTO · categoría (lender_users_categories) ────────────────────
  'cat.enganche': { label: 'Enganche (categoría)', tables: ['lender_users_categories.min_initial_fee'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'El enganche REAL de rt=2. Infla el cupo /(1−fee) y pisa al del comercio.',
    detail: 'Deriva el monto que cobra Wompi. Es el que manda para CreditopX.' },
  'cat.cupoMax': { label: 'Cupo máx (categoría)', tables: ['lender_users_categories.max_amount'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Techo de cupo por perfil de riesgo. Pisa al max_amount base (rt=2).', detail: 'Se combina con el fondo y la capacidad de pago para el cupo final.' },
  'cat.plazoMax': { label: 'Plazo máx (categoría)', tables: ['lender_users_categories.max_fee_number'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Techo de plazos de la categoría. Recorta la lista de cuotas; el tramo por monto recorta dentro.',
    detail: 'Intersección (AND) con el tramo: gana el más restrictivo.' },
  'cat.fondo': { label: 'Fondo (límite − usado)', tables: ['lender_users_categories.loan_limit / already_used_loan'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'El fondo que le queda al lender para este cliente. Topa el cupo.', detail: 'cupo = min(max_amount, loan_limit − already_used_loan), inflado por el enganche.' },
  'cat.capacidad': { label: 'Capacidad de pago', tables: ['lender_users_category_rules.min_debt_capacity / debt_capacity_amount_validation'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Topa el cupo por anualidad inversa sobre el ingreso (cuota máx = ingreso×%).',
    detail: 'debt_capacity_amount_validation==0 → rechaza por capacidad y usa el cupo por lender; ≠0 → usa el cupo del perfil (donde entra la tasa).' },
  'cat.minIncome': { label: 'Ingreso mín (regla)', tables: ['lender_users_category_rules.monthly_income'], layers: ['application', 'legacy-backend'], status: 'muerto',
    summary: '🐛 BUG: los 3 motores leen $rule->min_income (columna inexistente) en vez de monthly_income → el piso de ingreso NUNCA filtra a nadie.',
    detail: 'La columna física es monthly_income; el código lee min_income (no existe ni como accessor) → null → salario >= null pasa siempre. Confirmado en app (LenderUserCategoryService:111) y ambos servicios legacy. Arreglarlo ENDURECE la asignación de categorías.' },
  'cat.age': { label: 'Edad (regla)', tables: ['lender_users_category_rules.min_age / max_age'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Rango de edad que acepta la categoría.', detail: 'age entre min y max.' },
  'cat.continuity': { label: 'Continuidad mín (regla)', tables: ['lender_users_category_rules.employment_continuity'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Meses cotizando mínimos (de Ágil/Mareigua).', detail: 'Quanto = continuidad 0.' },
  'cat.verifiedIncome': { label: 'Ingreso verificado (regla)', tables: ['lender_users_category_rules.verified_income'], layers: ['application'], status: 'decide',
    summary: 'Exige que el ingreso venga del buró (no declarado).', pisaPor: '—',
    detail: '⚠️ Divergencia: solo application lo evalúa; legacy ignora la columna (migración solo-app 2025_12_19).' },
  'cat.occupation': { label: 'Ocupación (regla)', tables: ['lender_users_category_rules.occupation'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Ocupaciones aceptadas por la categoría.', detail: 'Formato CSV con | ; in_array contra field_id 29.' },
  'cat.gender': { label: 'Género (regla)', tables: ['lender_users_category_rules.gender'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Géneros aceptados por la categoría.', detail: 'Formato CSV con |.' },
  'cat.minScore': { label: 'Score mín (regla)', tables: ['lender_users_category_rules.min_score'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Score mínimo de datacrédito. Se solapa con el datacrédito temprano (se chequea 2 veces).', detail: '0 = sin exigencia.' },
  'cat.maxNegatives': { label: 'Negativos máx (regla)', tables: ['lender_users_category_rules.negative_reports_last_12_months'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Máx reportes negativos 12m aceptados.', detail: '≥20 = sin límite (sentinel mágico en el código real).' },
  'cat.maxDelinq': { label: 'Mora máx (regla)', tables: ['lender_users_category_rules.current_delinquencies'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Máx cuentas en mora vigente. Exclusiva de la categoría.', detail: '≥10 = sin límite.' },
  'cat.minHistory': { label: 'Antigüedad mín (regla)', tables: ['lender_users_category_rules.financial_history_length'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Antigüedad mínima del historial (meses).', detail: 'maturationSince → diffInMonths >= umbral.' },
  'cat.maxInquiries': { label: 'Consultas máx (regla)', tables: ['lender_users_category_rules.consulted_last_6_months'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Máx consultas al buró en 6m.', detail: '≥20/≥100 = sin límite.' },

  // ── TRAMO por monto (creditop_x_conditions_by_amount_by_lender) ────────────
  'tramo': { label: 'Tramo por monto', tables: ['creditop_x_conditions_by_amount_by_lender'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Último ajuste del cascade rt=2: según el monto pedido recorta plazos y topea el cupo. NO toca el enganche.',
    detail: 'El initial_fee_percentage del tramo es fantasma (nunca leído). min_amount/max_amount/max_fee_number/mandatory_fee_number sí deciden. Monto por debajo del 1er "desde" → rechazo.' },

  // ── 2ª CAPA · Config de sucursal (status + group_rules + datacrédito, COPIADAS) ──────
  'suc.status': { label: 'Estado en sucursal', tables: ['lenders_by_allied_branches.status'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Activa/desactiva la entidad EN ESA sucursal. Es la 1ª compuerta dura de getLenders: base = lenders_by_allied_branches (por sucursal, no por comercio).',
    detail: 'El comercio habilita la entidad en su catálogo (lenders_by_allieds); cada sucursal la prende o apaga por separado vía status. getLenders solo lista las filas activas → inactiva = NO se ofrece en la sucursal (filtro duro, antes de perfilar). La fila se COPIA por sucursal al habilitar la entidad (junto con url_utm/sort).' },
  'suc.datacredito': { label: 'Datacrédito por sucursal', tables: ['lender_datacredito_rules (allied_branch_id)'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Umbrales de buró por sucursal. Se COPIAN al habilitar la entidad (no se heredan).',
    detail: '⚠️ Miles de filas por entidad (7.183 totales; solo 107 con allied_branch_id NULL). Fallback silencioso a los umbrales de BdB (lender 5) si no hay plantilla. rt=2 que falla se EXCLUYE; rt≠2 solo se reordena.' },
  'suc.grouprules': { label: 'Group rules por sucursal', tables: ['group_rules + lender_rules (allied_branch_id)'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Reglas duras (AND dentro del grupo, OR entre grupos). También COPIADAS por sucursal.',
    detail: 'La plantilla (group_rule_id NULL) se clona en cada sucursal (~37k filas, deriva). Al fallar: rt=2 se excluye, rt≠2 baja al fondo (clasifica).' },

  // ── COMERCIO / SUCURSAL (contexto) ─────────────────────────────────────────
  'merch.nombre': { label: 'Comercio', tables: ['allieds.name'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'El aliado. Resuelve su calculadora económica (lenders_by_allieds) y ramifica hardcodes (ej. allied_id==94 Pullman).',
    detail: 'Hay hardcodes por id de comercio (Pullman 94, Corbeta [24,209,210,211], DENTIX 189) que deberían ser columnas de config.' },
  'merch.sucursal': { label: 'Sucursal', tables: ['allied_branches (hash)'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Punto de venta. Su hash es la LLAVE de entrada al flujo; define qué reglas (copiadas) aplican.',
    detail: 'El link con hash resuelve allied_branch_id + allied_id. La sucursal se reconstruye entera en cada save (DELETE + recreate).' },
  'canal.asesor': { label: 'Nombre asesor', tables: ['(propuesto)'], layers: ['frontend-monorepo', 'legacy-backend'], status: 'display',
    summary: 'Canal ASESOR: la solicitud entra por un asesor del comercio (wizard /merchant/*). El nombre identifica quién origina.',
    detail: 'Forward-looking: hoy el canal no es una columna de config; el nodo modela el deber-ser (canal = asesor | ecommerce).' },
  'canal.tienda': { label: 'Nombre de tienda', tables: ['(propuesto)'], layers: ['frontend-monorepo', 'legacy-backend'], status: 'display',
    summary: 'Canal ECOMMERCE: la solicitud entra por el checkout de la tienda. El nombre identifica la tienda online.',
    detail: 'Forward-looking: mismo nodo Canal, rama ecommerce. Más adelante ramifica el flujo (checkout vs wizard de asesor).' },

  // ══ NODOS (headers) — vista rica de toda la etapa/tabla (kind: 'node') ══════
  'node.comercio': { kind: 'node', stage: 'contexto', label: 'Comercio', layers: ['application', 'legacy-backend'],
    tables: ['allieds (comercio + flags)', 'allied_branches (sucursal + hash)'],
    role: 'El comercio aliado y su sucursal: el contexto que resuelve toda la oferta.',
    bullets: ['El hash de la SUCURSAL es la llave de entrada al flujo (resuelve allied_id + allied_branch_id).',
      'El nombre del comercio resuelve su calculadora económica (lenders_by_allieds).',
      'have_ctopx ramifica lógica pero NO es el gate duro de la oferta rt=2.',
      'Hardcodes por id que deberían ser config: Pullman 94, Corbeta [24,209,210,211], DENTIX 189.'],
    detail: 'El alta NO cablea la relación lender↔sucursal: eso ocurre al habilitar la entidad en la sucursal (S2), que además COPIA las reglas.', evidencia: 'MAP.md §S1-S2' },
  'node.canal': { kind: 'node', stage: 'contexto', label: 'Canal', layers: ['frontend-monorepo', 'legacy-backend'],
    tables: ['(propuesto)'],
    role: 'Por dónde ENTRA la solicitud: asesor (en el comercio) o ecommerce (checkout de la tienda).',
    bullets: ['Asesor → wizard /merchant/* operado por un asesor; el nombre identifica quién origina.',
      'Ecommerce → checkout de la tienda online; el nombre identifica la tienda.',
      'Hoy es contexto (una etiqueta); más adelante el nodo ramifica el flujo (wizard vs checkout).'],
    detail: 'Forward-looking: el canal aún no es una columna de config; este nodo modela el deber-ser para preparar la bifurcación asesor/ecommerce.' },
  'node.lendersCfg': { kind: 'node', stage: 'config', label: 'Entidades del comercio', layers: ['application', 'legacy-backend'],
    tables: ['lenders', 'lenders_by_allied_branches (base sucursal)', 'lender_allied_credentials (credencial)'],
    role: 'El catálogo: qué entidades ofrece esta sucursal y con qué response_type.',
    bullets: ['Visibilidad = base por sucursal → filtros duros (status/país/datacrédito) → group_rules → categoría (rt=2).',
      'CreditopX / agregador / redirect son solo el response_type de un lender.',
      'Sin fila en lender_allied_credentials (por allied_id), aunque se ofrezca, el flujo falla.'],
    detail: 'En el simulador el catálogo son las entidades que creás (persisten en localStorage); en real es lenders_by_allied_branches por sucursal.', evidencia: 'lender-listing-cascade · MAP.md §S5' },

  // ── Post-selección (ciclo de vida después de elegir, estado 3) ──
  'node.lifecycle': { kind: 'node', stage: 'post-selección', label: 'Formalización', layers: ['legacy-backend', 'frontend-monorepo', 'application'],
    tables: ['user_requests (estado 3 → 11)'],
    role: 'La FORMALIZACIÓN después de elegir (estado 3 = "Seleccion de entidad"): el journey hasta el desembolso.',
    bullets: ['La cadena se ramifica por response_type: rt=2/3 corre local (KYC→firma→enganche→11); rt=1 formaliza afuera; rt=0 redirige.',
      'Cada paso es un toggle (tocá el círculo para simular que falla); la cascada se recalcula.',
      'rt=1 la pre-aprobación YA fue en el listado — acá es la 2ª decisión externa (no inyectable desde BD).'],
    detail: 'Estado terminal = una función pura de (rt + toggles). Mora/cartera post-11 es otro grafo.', evidencia: 'FLUJO-CREDITOPX §journey · CONTINUACION-CREDITO' },
  'psel.plan': { kind: 'node', stage: 'post-selección', label: 'Plan de pagos', layers: ['legacy-backend', 'frontend-monorepo'],
    tables: ['payment_schedules', 'first_payment_dates'],
    role: 'Después de elegir (rt=2): se define el plazo y la 1ª fecha, y se arma el cronograma real.',
    bullets: ['El plazo se elige ACÁ; en el listado la cuota es solo una estimación.',
      'Cuota = capital (financiado + costos admin + fondo·IVA 19%) → anualidad(tasa, plazo) + seguros.',
      'Guards: si ya está desembolsado/cancelado, redirige (no re-arma el plan).'],
    detail: 'GetPaymentSchedulesUc / GetFirstPaymentDatesUc.', evidencia: 'FLUJO-CREDITOPX §journey (pasos 1-3)' },
  'psel.kyc': { kind: 'node', stage: 'post-selección', label: 'KYC · biométrico (ADO)', layers: ['legacy-backend'],
    tables: ['risk_central_user_data', 'RiskCentrals/Ado'],
    role: 'Liveness/biometría de formalización, en el portal EXTERNO de ADO (navegación de página completa, no iframe).',
    bullets: ['Enroll → callback a identity-validation-status → polling StatusCheck (re-despacho 2s) → evento Echo.',
      'ADO se da por validado con state_id == 2.',
      'NO es el KYC inicial: la identidad/AML (TusDatos) del gate de viabilidad corre ANTES del listado. Para Credifamilia V2 es Jumio/Evidente.'],
    detail: 'La posición exacta de la liveness post-selección es capa interpretativa (los docs no la fijan con line-ref).', evidencia: 'FLUJO-CREDITOPX §1-2 (AdoController)' },
  'psel.firma': { kind: 'node', stage: 'post-selección', label: 'Firma del pagaré', layers: ['legacy-backend', 'frontend-monorepo'],
    tables: ['user_requests (→ "Autorizado pendiente desembolso")'],
    role: 'Pagaré + OTP: verificar el OTP transiciona al estado intermedio; autorizar lleva al Estado 11.',
    bullets: ['send-otp → verify-otp (transitionToIntermediate) → authorize.',
      'authorize → loanAuthorizationService->authorize → Estado 11 + firma real (Netco/Deceval) + notifyEcommerceStore.',
      'Rechaza si ya está autorizado / en Estado 11.'],
    detail: 'ValidateOtpPromissoryNoteController::verifyOtp/disburse.', evidencia: 'FLUJO-CREDITOPX §6' },
  'psel.enganche': { kind: 'node', stage: 'post-selección', label: 'Cobro del enganche (Wompi)', layers: ['legacy-backend', 'frontend-monorepo'],
    tables: ['(checkout hospedado Wompi)'],
    role: 'Cobro del enganche cuando aplica (initial_fee > 0), vía checkout de Wompi. Cierra el lazo con la categoría.',
    bullets: ['El enganche lo FIJA la categoría de perfilamiento (rt=2), no el comercio.',
      'initiate → checkout_url → redirect Wompi → down-payment-validation; confirmación por evento Echo.',
      'Ya NO hay ramas initial_fee/standBy en la action de selección: el enganche es un paso del journey.'],
    detail: 'Si el caso no exige enganche, el paso se salta y se sella el Estado 11 en la firma.', evidencia: 'FLUJO-CREDITOPX §9 (InitialFeePaymentController)' },
  'psel.radica': { kind: 'node', stage: 'post-selección', label: 'Radicación (rt=1)', layers: ['legacy-backend', 'application'],
    tables: ['(API externa del lender)'],
    role: 'Se manda la solicitud FORMAL a la API del agregador. Segunda decisión externa.',
    bullets: ['La pre-aprobación (con cupo) ya ocurrió en el listado: radicar ≠ pre-aprobar.',
      'Credifamilia (rt=4) es asíncrona: carrera timeout-front 40s vs write-timeout MS 30s.',
      'NO es inyectable localmente: el toggle es "ficción honesta".'],
    detail: 'La cadena rt=1 modela una decisión que en la realidad no se fuerza desde BD.', evidencia: 'pre-approvals-service · synth-lender-type-boundary' },
  'psel.decision': { kind: 'node', stage: 'post-selección', label: 'Decisión externa (su API)', layers: ['legacy-backend', 'application'],
    tables: ['webhook lender-result → user_request_status_id'],
    role: 'El proveedor formaliza y el resultado vuelve por webhook, espejado a legacy.',
    bullets: ['aprueba / rechaza / timeout ("en proceso").',
      'Los webhooks de los agregadores siguen viviendo en application (CreditopX rt=2 ya migrado).',
      'Mapeo estado externo → id: BdB Disbursed→11, Failed→7, Pending→10.'],
    detail: 'Divergencia app↔legacy (best-effort): puede derivar lo que ve el usuario vs lo que persiste.', evidencia: 'CONTINUACION-CREDITO §mapeo' },
  'psel.redirect': { kind: 'node', stage: 'post-selección', label: 'Redirección (rt=0)', layers: ['legacy-backend'],
    tables: ['lenders_by_allied_branches.url_utm'],
    role: 'CreditOp escribe la url_utm, redirige al sitio del lender y pierde visibilidad total.',
    bullets: ['La decisión, el monto y el desenlace ocurren afuera.',
      'No hay Estado 11 rastreable: la plataforma no sabe si el crédito se dio.',
      'Contraste máximo con rt=2 (todo local).'],
    detail: 'rt=0 es un callejón sin salida para la plataforma.', evidencia: 'modelos-canales-flujos' },
  'psel.terminal': { kind: 'node', stage: 'post-selección', label: 'Estado del crédito', layers: ['legacy-backend', 'application'],
    tables: ['user_request_statuses (originación)', 'creditop_x_user_request_statuses (préstamo vivo)'],
    role: 'El desenlace de la solicitud según el rt.',
    bullets: ['rt=2/3 → Estado 11 "Autorizada" (terminal de originación) + aviso a la tienda.',
      'rt=1 → radicado / rechazado / timeout; la cartera queda del lender.',
      'rt=0 → desconocido (fuera de la plataforma).'],
    detail: 'Dos máquinas de estado se confunden: originación (hasta 11/26) ≠ préstamo vivo (1/2/3/4); el 11 es el puente. Mora/cartera es otro grafo.', evidencia: 'CONTINUACION-CREDITO §2 máquinas' },
  'node.solicitud': { kind: 'node', stage: 'onboarding', label: 'Solicitud', layers: ['application', 'legacy-backend', 'frontend-monorepo'],
    tables: ['user_requests', 'user_request_records (historial)', 'user_field_values (form dinámico)'],
    role: 'La solicitud del cliente (user_request) y sus inputs. Es el sujeto que evalúan las reglas.',
    bullets: ['La UR NO nace en el simulador: se crea tarde, al validar OTP / guardar info (estado 1→9).',
      'El monto entra por 3 orígenes según canal: sesión (asesor), base64 (ecommerce), body del OTP (wizard).',
      'La solicitud se RECICLA: reutiliza una previa en estados [1,3,9] del mismo user+sucursal.'],
    detail: 'El simulador modela los inputs que alimentan la DECISIÓN (monto/doc), no el arranque real (hash/celular/OTP), que es onboarding.', evidencia: 'MAP.md §S3' },
  'node.experian': { kind: 'node', stage: 'buró', label: 'Datacrédito · Experian', layers: ['application', 'legacy-backend'],
    tables: ['risk_central_user_data.data (cifrado APP_KEY) + .score', 'user_summaries.datacredito', 'user_field_values (EAV 87/29/160/90)'],
    role: 'El ÚNICO buró que da SCORE. Alimenta los dos motores de datacrédito.',
    bullets: ['OAuth2 + POST /cs/credit-history/v1/hdcplus (Acierta=score, Quanto=ingreso).',
      'En local/dev se MOCKEA con ExperianFixture → el score de dev es sintético.',
      'DOS motores con campos y comparadores DISTINTOS: viejo rt≠2 (maduración <=) vs nuevo rt=2 (score>=, maduración <).',
      'El mapper (reporte → EAV/summary) vive en application; kyc-gateway (Go) lo reimplementa pero está muerto.'],
    detail: 'El score se persiste plano + el reporte crudo cifrado. Los DOS backends tienen cliente Experian completo (parallel-run).', evidencia: 'MAP.md §S4 · Experian.php' },
  'node.agil': { kind: 'node', stage: 'buró', label: 'Ágil Data', layers: ['application', 'legacy-backend'],
    tables: ['user_summaries.agildata', 'user_field_values (87 ingreso, 29 ocupación)'],
    role: 'Ingreso y empleo. 1ª fuente de la cascada de ingreso; aporta edad y género.',
    bullets: ['Ganа sobre Mareigua/Ábaco/Quanto/declarado si reporta ingreso.',
      'La edad NO viene del buró: se calcula de date_of_birth.',
      '⚠ Al procesar Quanto se fuerza EAV 29="Empleado" y 160="no" (hardcodeados).'],
    detail: 'Es KYC de ingreso/empleo, no score. Alimenta capacidad de pago y las reglas de ocupación/edad/género/continuidad.', evidencia: 'MAP.md §S4' },
  'node.tusdatos': { kind: 'node', stage: 'buró', label: 'TusDatos', layers: ['application', 'legacy-backend'],
    tables: ['user_summaries.tusdatos'],
    role: 'Validación de identidad + AML (listas restrictivas). No da score.',
    bullets: ['Identidad verificada y AML pueden ser reglas duras (requireVerifiedIdentity / requireCleanAml).',
      'SmartPay (canal) SALTA el AML de TusDatos y usa mailer propio.',
      '"PEP" en AML = Persona Expuesta Políticamente (≠ PEP migratorio de Motai).'],
    detail: 'KYC de identidad/antifraude. El estado del documento (vigente/cancelado) se entrega pero no gatea el listado en el simulador.', evidencia: 'MAP.md §S4' },
  'node.mareigua': { kind: 'node', stage: 'buró', label: 'Mareigua', layers: ['application', 'legacy-backend'],
    tables: ['user_summaries.mareigua'],
    role: 'Ingreso de respaldo (2ª fuente, fallback de Ágil) + continuidad y tendencia.',
    bullets: ['Solo entra si Ágil Data no reportó ingreso.', 'La tendencia de ingreso se entrega pero no decide.'],
    detail: 'Central alterna de ingreso/empleo.', evidencia: 'MAP.md §S4' },
  'node.abaco': { kind: 'node', stage: 'buró', label: 'Ábaco', layers: ['application', 'legacy-backend'],
    tables: ['user_summaries.abaco'],
    role: 'Ingreso de economía gig (Rappi/DiDi/Uber). Underwriting alternativo sin buró (Motai renting).',
    bullets: ['3ª fuente de la cascada de ingreso.',
      'Proveedor EXTERNO: CreditOp solo consume su API. Ábaco pide las credenciales de acceso del cliente a cada plataforma (Rappi/Didi/Uber), entra y devuelve un resumen de ingresos mensuales.',
      '⚠ Divergencia: el resultado de Ábaco NO está cableado a la decisión en legacy (queda huérfano) — el simulador lo sobre-modela.'],
    detail: 'Apunta a población gig/migrante (PEP = Permiso Especial de Permanencia) sin historial de buró tradicional.', evidencia: 'MOTAI-FLUJO-ANALISIS.md' },
  'node.buro': { kind: 'node', stage: 'buró', label: 'Perfil consolidado', layers: ['application', 'legacy-backend'],
    tables: ['risk_central_user_data', 'user_summaries'],
    role: 'Junta todos los burós y arma el SUJETO que evalúan las reglas.',
    bullets: ['Cascada de ingreso: Ágil → Mareigua → Ábaco → Quanto → declarado → 0.',
      'Score único (Experian). Endeudamiento DERIVADO (cuota deuda ÷ ingreso).',
      'Fail-closed: un dato en null o una API caída hace fallar la regla que lo necesita.'],
    detail: 'Es el resumen enriquecido (user_summaries) sobre el que corre toda la decisión.', evidencia: 'MAP.md §S4' },
  'node.out': { kind: 'node', stage: 'salida', label: 'Entidades disponibles', layers: ['application', 'legacy-backend', 'frontend-monorepo', 'pre-approvals'],
    tables: ['lenders_by_allied_branches (base)', 'displayed_lenders / profiling_reviews (snapshot)'],
    role: 'El marketplace: getLenders arma el listado ofrecido. ⚠ Lo mostrado ≠ lo que decide el punto de venta.',
    bullets: ['getLenders = 8 etapas: base → group_rules+datacrédito → ML/matrices → especiales → pre-aprobados rt=1 → orden → CATEGORÍA+tramo (corte final).',
      'rt=2 que falla se EXCLUYE; rt≠2 que falla se CLASIFICA al fondo (prob. baja).',
      'El 2º motor autoritativo /available-quota re-decide en el POS — NO está en el simulador.',
      'El orden usa ML (H2O.ai) pero está corto-circuitado → cae a matrices internas.'],
    detail: 'rt=1 lo resuelve el MS Go pre-approvals-service (wizard) o el PHP viejo; la decisión es de la API externa (no inyectable).', evidencia: 'MAP.md §S5-S6' },
  'node.default': { kind: 'node', stage: 'config', label: 'Configurar entidad', layers: ['application', 'legacy-backend'],
    tables: ['credit_line_by_lenders (monto/cuotas/tasa)', 'lenders_by_allieds (override comercio)', 'lender_users_categories (cupo rt=2)', 'creditop_x_lender_configuration'],
    role: 'La config de la entidad (lo que edita el admin en "Editar entidad"): producto + economía base.',
    bullets: ['La economía NO vive en la tabla lenders: se reparte en 3-4 tablas.',
      'Para rt=2 la CATEGORÍA manda (pisa monto/cuotas/enganche del comercio y la base).',
      'product_type es fantasma: se modela con response_type + path (ej. IMEI).'],
    detail: 'credit_line_by_lenders es hasOne (1 fila por lender). Muchas columnas de aquí están muertas o pisadas — ver los campos.', evidencia: 'CENSO-CAMPOS-CONFIG.md' },
  'node.comercioConfig': { kind: 'node', stage: 'config', label: 'Configurar comercio', layers: ['application', 'legacy-backend'],
    tables: ['lenders_by_allieds (la calculadora)'],
    role: 'La calculadora económica del comercio: qué le cuesta el crédito al cliente y qué gana CreditOp.',
    bullets: ['Costos admin, cargo fijo, fondo de garantías (·1.19) y seguros se SUMAN a la cuota.',
      'La comisión es cobro al COMERCIO (revenue), no toca la cuota del cliente.',
      'Varios campos MUERTOS (iva, castigo, múltiplo) y el enganche lo decide la categoría, no el comercio.'],
    detail: 'Es el nivel "comercio" (lenders_by_allieds). Para el producto insignia rt=2, gran parte es cosmética.', evidencia: 'CENSO-CAMPOS-CONFIG.md §2' },
  'node.relacion': { kind: 'node', stage: 'decisión', label: 'Configurar sucursal', layers: ['application', 'legacy-backend'],
    tables: ['group_rules + lender_rules (duras)', 'lender_datacredito_rules (buró)'],
    role: '2ª capa del cascade: reglas duras + datacrédito, COPIADAS por sucursal. Corren ANTES del perfilamiento.',
    bullets: ['Se COPIAN al habilitar la entidad (~37k filas, deriva, huérfanas al desactivar) en vez de heredar.',
      'Al fallar: rt=2 se EXCLUYE; rt≠2 se clasifica al fondo (datacrédito rt≠2 solo reordena).',
      'Fallback silencioso a los umbrales de BdB (lender 5) si no hay plantilla.'],
    detail: 'Group rules: AND dentro del grupo, OR entre grupos. La copia es el mecanismo real de config por sucursal — y su mayor deuda.', evidencia: 'HALLAZGO-GESTION-REGLAS-POR-SUCURSAL.md' },
  'node.perfil': { kind: 'node', stage: 'decisión', label: 'Perfilamiento', layers: ['application', 'legacy-backend'],
    tables: ['lender_users_categories', 'lender_users_category_rules'],
    role: 'El corazón de rt=2: la categoría del cliente decide enganche/cupo/plazo. Es el corte FINAL del cascade.',
    bullets: ['El usuario cae en la 1ª categoría (por prioridad) cuya regla cumple.',
      'Cupo = min(max_amount, fondo)/(1−enganche), topeado por capacidad de pago.',
      'El riesgo (score/negativos/mora/consultas) vive DENTRO de la regla de categoría, por lender_id.',
      '⚠ priority solo ordena en application; legacy ordena por category_id → el ganador puede diferir.'],
    detail: 'Sin categoría (o documento en lista negra) → no se ofrece. Para rt=1 no perfila: la API externa decide.', evidencia: 'MAP.md §S5 · CENSO §categorías' },

  // ── MARKETPLACE (tarjetas de "Entidades disponibles") + catálogo ────────────
  'mk.rt': { label: 'Tipo de respuesta (rt)', tables: ['lenders.response_type'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Quién decide el crédito: rt2 CreditopX (CreditOp, local) · rt1 agregador (la API del banco) · rt0 redirect (su sitio).',
    detail: 'Es el eje que define el flujo entero: rt=2 decide con categorías locales y cierra in-platform (Estado 11); rt=1 pre-aprueba vía API externa (no inyectable); rt=0 solo redirige y el crédito no vuelve.' },
  'mk.cupo': { label: 'Cupo mostrado', tables: ['lender_users_categories (rt=2)', 'respuesta del preaprobado (rt=1, available)'], layers: ['application', 'legacy-backend', 'pre-approvals'], status: 'decide',
    summary: 'rt=2: calculado LOCAL = min(monto, cupo de la categoría, tope del comercio, tramo). rt≠2: tope configurado — el cupo real lo trae la API del banco.',
    detail: '⚠ Lo mostrado ≠ lo que decide el punto de venta: el 2º motor (/available-quota) re-decide al confirmar. Para rt=1, "available" viene horneado en la respuesta externa.' },
  'mk.cat': { label: 'Categoría (chip)', tables: ['lender_users_categories'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'La categoría de perfilamiento en la que cayó ESTE usuario para ESTA entidad (rt=2). Es la que fija enganche/cupo/plazo.',
    detail: 'Se resuelve al final del cascade (1ª categoría por prioridad cuya regla cumple). Sin categoría → la entidad no se ofrece.' },
  'mk.inicial': { label: 'Cuota inicial (de la tarjeta)', tables: ['category.min_initial_fee → user_requests.initial_fee'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'El enganche que EXIGE la categoría ganadora, en $ sobre el monto pedido. Se cobra vía Wompi antes de continuar (rt=2).',
    detail: 'El % viene de la categoría (no del comercio: el de lenders_by_allieds se pisa). Monto = % × monto pedido.' },
  'mk.cuota': { label: 'Cuota estimada (y plazo)', tables: ['credit_line_by_lenders.fee_numbers (plazos)', '(la cuota se calcula, no se persiste hasta originar)'], layers: ['application', 'legacy-backend', 'frontend-monorepo'], status: 'display',
    summary: 'Estimador: anualidad francesa sobre capital = financiado + costos admin + FGA·1.19, + seguros (IVA 19% quemado). El selector de plazo acá solo estima.',
    detail: 'rt=2: el plazo REAL se elige DESPUÉS, en el plan de pagos (/confirmar-cuotas · payment-schedule). rt=1: los plazos vienen resueltos por el banco dentro de transaction_data (cada lender con su forma).' },
  'mk.prob': { label: 'Probabilidad baja (badge)', tables: ['group_rules / lender_datacredito_rules (por sucursal)'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Una entidad rt≠2 que falla la 2ª capa NO se excluye: se conserva al fondo del listado como "probabilidad baja".',
    detail: 'La inversión clave del cascade: rt=2 que falla se EXCLUYE; rt≠2 solo se clasifica (reordena). Por eso "salió aprobado pero de último" no es un error.' },
  'cfg.producto': { label: 'Producto (chip)', tables: ['(sin columna: response_type + path)'], layers: ['application', 'legacy-backend'], status: 'decide',
    summary: 'Crédito / renting / renting con compra. product_type NO existe como columna en la BD: se infiere de response_type + path (ej. IMEI).',
    detail: 'Mismo hallazgo que "Producto" en Configurar entidad: el tipo de producto real es una columna a crear (deber-ser).' },

  // ── Descripción de cada CATEGORÍA (header de la tarjeta) ────────────────────
  'catnode.A': { kind: 'node', stage: 'decisión', label: 'Categoría A · Premium', layers: ['application', 'legacy-backend'],
    tables: ['lender_users_categories', 'lender_users_category_rules'],
    role: 'El MEJOR perfil. El usuario cae acá si cumple TODAS sus condiciones (se evalúa primero, prioridad 1).',
    bullets: ['Ofrece lo mejor: enganche más bajo y cupo más alto.',
      'Exige lo más estricto: score alto, ingreso verificado, poca mora/consultas.',
      'Si falla una condición (campo en rojo), NO cae acá → se prueba la siguiente (Estándar).'],
    detail: 'La 1ra categoría (por prioridad) cuya regla cumple GANA y fija enganche/cupo/plazo. Premium es la más exigente y la más generosa.' },
  'catnode.B': { kind: 'node', stage: 'decisión', label: 'Categoría B · Estándar', layers: ['application', 'legacy-backend'],
    tables: ['lender_users_categories', 'lender_users_category_rules'],
    role: 'Perfil INTERMEDIO. Cae acá si no calificó para Premium pero cumple estas condiciones (prioridad 2).',
    bullets: ['Enganche y cupo intermedios.',
      'Requisitos más laxos que Premium (score / ingreso menores).',
      'Si tampoco cumple (campo en rojo), se prueba Básica.'],
    detail: 'Es el punto medio: el grueso de los clientes suele caer acá.' },
  'catnode.C': { kind: 'node', stage: 'decisión', label: 'Categoría C · Básica', layers: ['application', 'legacy-backend'],
    tables: ['lender_users_categories', 'lender_users_category_rules'],
    role: 'El perfil más PERMISIVO (catch-all). Cae acá si no calificó para las anteriores pero cumple lo mínimo (prioridad 3).',
    bullets: ['Enganche más alto y cupo más bajo (el crédito más caro/chico).',
      'Requisitos mínimos: acepta casi a cualquiera.',
      'Si NI esta cumple → sin categoría → la entidad NO se ofrece.'],
    detail: 'Es la última red: si Básica tampoco pasa, el lender rt=2 se excluye del listado.' },
}

// Etapa del nodo (badge del sidebar cuando kind==='node').
export const NODE_STAGE = {
  contexto:   { label: 'Contexto' },
  onboarding: { label: 'Onboarding' },
  'buró':     { label: 'Buró / KYC' },
  config:     { label: 'Configuración' },
  'decisión': { label: 'Decisión' },
  salida:     { label: 'Salida' },
}
